image: alpine:edge

build:
  tags:
  - plmshift
  variables:
    disk_image: 'pxeboot'
  script:
  - apk update
  - apk add bash git make gcc perl musl-dev xz-dev openssl-dev openssl sed coreutils curl
  - cd ${CI_PROJECT_DIR}
  - bash build.bash ${disk_image}
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/ipxe.raw