image: alpine:edge

pages:
  tags:
  - plmshift
  script:
  - apk update
  - apk add bash git make gcc perl musl-dev xz-dev openssl-dev openssl sed coreutils curl
  - cd ${CI_PROJECT_DIR}
  - bash build.bash
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/public
