image: alpine:edge

build:
  script:
  - apk update
  - apk add bash syslinux sudo qemu-img xz
  - apk add libguestfs --repository http://dl-3.alpinelinux.org/alpine/edge/testing
  - mkdir /usr/lib/guestfs
  - cd /usr/lib/guestfs
  - wget http://download.libguestfs.org/binaries/appliance/appliance-1.40.1.tar.xz
  - unxz appliance-1.40.1.tar.xz
  - tar xvf appliance-1.40.1.tar
  - cd ${CI_PROJECT_DIR}
  - bash build.bash